### ISSUE TITLE
Not finding functions

### ISSUE THREAD

**Issue by skwny** [gramstr/better-firebase-functions#12]
Hi, none of my functions are building with this. I'm using as follows:

```
import { exportFunctions } from 'better-firebase-functions';

exportFunctions({
  // standard node var (leave as is).
  __filename,
  // standard node var (leave as is).
  exports,
  // define root functions folder relative to this file.
  functionDirectoryPath: './app/functions/*',
  searchGlob: '**/*.f.ts',
})
```

Normally I use `ng build` to handle the build, not sure if that matters.

**Comment by dmba** [comment]
@skwny I think you need to change `**/*.f.ts` to `**/*.f.js`.

**Comment by george43g** [comment]
The github code has been updated with a sensible default now, searching for both ts and js files.
