### ISSUE TITLE
Issue deploying functions in nested folders?

### ISSUE THREAD

**Issue by danmalone89** [gramstr/better-firebase-functions#15]
I have a functions src folder like so

- src
  - http
    someFunction.ts
      - stripe
        stripeFunction.ts

someFunction.ts deploys just fine with BFF. However, I receive a 400 error on the stripeFunction.ts error when using `firebase deploy --only functions`. 

This is the error I receive in my console, however the recommended command doesn't work either. If I move stripeFunction to the http folder, then it deploys fine, but not from the stripe folder.

```
Functions deploy had errors with the following functions:
        http-stripe\stripeFunction

To try redeploying those functions, run:
    firebase deploy --only functions:http.stripe\stripeFunction
```

**Comment by george43g** [comment]
I believe deeply nested folders were broken for a while. These should work now. Please reopen this issue if it still exists for you.
