### ISSUE TITLE
Javascript - firebase deploy just exits

### ISSUE THREAD

**Issue by simeon9696** [gramstr/better-firebase-functions#17]
Hey! This is a really sweet package and I would like to use it in my JS project. I couldn't find much reference to JS in the docs and I'm a bit of a beginner so I apologise if this question is straightforward. 

I set up the folder structure as mentioned: 
![image](https://user-images.githubusercontent.com/31748055/98950279-2e62f700-24cf-11eb-982c-8d2bc18261eb.png)

And inside of index.js all I have is, taken from [this issue,]([url](https://github.com/gramstr/better-firebase-functions/issues/4#issuecomment-629932791)) :

```
const admin = require('firebase-admin');
admin.initializeApp();
require('better-firebase-functions').exportFunctions({__filename, exports: module.exports});
```

All my functions are structured like below: 
```
"use strict";
const functions = require("firebase-functions");
const admin = require("firebase-admin");

module.exports.default = functions.firestore
  .document("items/{item}")
  .onCreate(async (doc, context) => {
    const db = admin.firestore();
    return db.doc("GLOBAL_DATA/GENERAL_DATA").update({
      itemCodes: admin.firestore.FieldValue.arrayUnion(doc.id),
      batchNumbers: admin.firestore.FieldValue.arrayUnion(
        doc.data().generalData.batchNumber
      )
    });
  });
```

But if I run firebase deploy  it starts up and then exits:

`firebase deploy --only functions`

```
PS C:\Users\simeon.ramjit\Documents\projects\plant-order-form\functions> firebase deploy --only functions:scheduled
=== Deploying to 'plant-order-form'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint C:\Users\simeon.ramjit\Documents\projects\plant-order-form\functions
> eslint .

+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
PS C:\Users\simeon.ramjit\Documents\projects\plant-order-form\functions> 
```

I'm running Node v10 and I tried putting the `api` folder into a folder named `src` flag I'd appreciate any assistance on this.

**Comment by LeadDreamer** [comment]
I found a problem with deep function trees - the name generator wasn't formatting quite properly.  I've created a pull request to fix this; waiting for it to be expected; currently using a local copy to get around this.  If I don't see action in a week or so I guess I'll have to release my own package.

**Comment by polymer-coder** [comment]
@LeadDreamer thanks for your work! Let's hope it gets added soon.

**Comment by polymer-coder** [comment]
@LeadDreamer @george43g Hi! any update on this?

**Comment by george43g** [comment]
Hey guys, just cleaning up old issues - newer versions of this package have fixed the deeply nested issue.
