### ISSUE TITLE
funcNameFromRelPath should not be hardcoded

### ISSUE THREAD

**Issue by atereshkov** [gramstr/better-firebase-functions#2]
funcNameFromRelPath should be configurable

thanks for the lib

**Comment by george43g** [comment]
I'll definitely revisit this when I have some spare time - I'm hoping the community can submit some pull requests and fix the CI configuration issues I'm having.

How would you like it to be configurable? Maybe allow people to choose between using a default export from each file VS multiple exports per file, and hence configure how the function is named?

**Comment by george43g** [comment]
version 4 will have this ability in the new and improved `exportFunctions()` function. This should be available within days.
