### ISSUE TITLE
Function in nested folder not working

### ISSUE THREAD

**Issue by theochampion** [gramstr/better-firebase-functions#21]
Hi there!

I'm trying to export functions from the following folder structure:

```
- src/
   -https/
       -recipe/
            create.func.ts
            read.func.ts
```

I was expecting the output to be two functions named:

```
https-recipe-create
https-recipe-read
```

Instead, it seems to take into account only the first two folder level and generate two functions

```
https-recipe
https-recipe
```

Which of course cannot be deployed:

```
HTTP Error: 409, Function https-recipe in region europe-west1 in project myapp already exists
```

Weird thing is that, if I remove one level of nesting (remove /recipe in between), they deploy properly.

Am I missing anything?

Cheers! 😃

**Comment by theochampion** [comment]
Any updates on this ? I can't seem to find a way around that problem and it's the very reason I wanted to use this package in the first place

**Comment by ivan416** [comment]
Experiencing the same problem. There seems to be a bug with nested folder structure.

**Comment by blasco** [comment]
Same situation here

**Comment by george43g** [comment]
Closing this issue as this is now fixed
