### ISSUE TITLE
Library keeps creating deleted function

### ISSUE THREAD

**Issue by NorbertHuethmayr** [gramstr/better-firebase-functions#34]
I'm running into a weird issue where a function that has been renamed keeps being deployed. Has anyone seen that before?

![image](https://user-images.githubusercontent.com/26460692/148664493-a8bfcab5-00e1-4949-ac68-3476d19b5743.png)

**Comment by roomman** [comment]
Deleting `/lib` (or whatever your output dir is called) and rebuilding fixed it for me. I hope that solves it for you too 🤞🏻

**Comment by NorbertHuethmayr** [comment]
> Deleting `/lib` (or whatever your output dir is called) and rebuilding fixed it for me. I hope that solves it for you too 🤞🏻

Worked like a charm - I didn't even know that there was such a *temp* directory.

**Comment by george43g** [comment]
This would happen because your old build files are still in the output directory, and bff scans this directory to find your functions. Don't think this is something this lib can fix.
